### ISSUE TITLE
Awards column

### ISSUE THREAD

**Issue by magdalenammcc** [Gawasinspire/Team_Hufflepuff#10]
I need to count the number of awards per book. 

Right now, the awards column has a string. I know it needs to be split by commas, and put into a list. 

Does it make sense to do it in the original web-scraped file? or in the analysis script?

Thank you!

**Comment by Gawasinspire** [comment]
Unfortunately, Fixed that already
https://github.com/Gawasinspire/Team_Hufflepuff/commit/4605ffbbb3f356c999587e72b1e3ca1527364f15

**Comment by Gawasinspire** [comment]
Please, Check this page often

https://github.com/Gawasinspire/Team_Hufflepuff/projects/1
