### ISSUE TITLE
Mean normalization

### ISSUE THREAD

**Issue by alessiorecchia** [Gawasinspire/Team_Hufflepuff#12]
Not sure who is in charge... Can someone update the mean normalization formula according to the new one, please? 
Thank you!

**Comment by Gawasinspire** [comment]
I could not able to find the updated formula or i see no difference. 
![image](https://user-images.githubusercontent.com/54960896/114799310-a5aaf880-9d97-11eb-80c5-369b89006d3f.png)

**Comment by Gawasinspire** [comment]
reopen this issue if you are not convinced

**Comment by alessiorecchia** [comment]
Didn't see this notification, I'm sorry. The new formula was this one:
df['mean_norm_ratings'] = (1 + (df['avg_rating'] - df['avg_rating'].mean()) / (df['avg_rating'].max() - df['avg_rating'].min())) * 4.5 +1

I thought you found it in the code I uploaded (I really need to be crystal clear with comments)
