### ISSUE TITLE
100 Rows CSV is missing num_ratings

### ISSUE THREAD

**Issue by Josh-Batt** [Gawasinspire/Team_Hufflepuff#4]
Currently have: 
Number of reviews (column 3)
Average review rating (column 4) 

But we are missing:
Number of ratings

Task 1 requires I have the number of ratings but no rush, I will work with the number of reviews in the mean time

**Comment by Gawasinspire** [comment]
https://github.com/Gawasinspire/Team_Hufflepuff/blob/gawas/selenium-firefox/500_rows.csv


Fixed :+1:  :)
