### ISSUE TITLE
gitignore file

### ISSUE THREAD

**Issue by alessiorecchia** [Gawasinspire/Team_Hufflepuff#8]
Hi Gavaskar,

could you please create a .gitignore file, so that some files (e.g. .ipynb_checkpoints) will be automatically skipped?

do it only if you have time and you think it can be useful!

**Comment by Gawasinspire** [comment]
yes it could be useful. Let me create it in master branch

**Comment by Gawasinspire** [comment]
Fixed 
https://github.com/Gawasinspire/Team_Hufflepuff/commit/e3af8bbb84324746d3880badea5dd499014ef2c8
